@ECHO OFF

IF "%1"=="" echo Missing host and port of NpcServerExample that is running & goto END
IF "%2"=="" echo Missing port of NpcServerExample that is running & goto END

echo Generating classes and types from server %1 on port %2...

.\bin\Debug\NpcClientGenerator.exe %1 %2 --methods --xmlcomments > ..\NpcClientExample\AutogeneratedClient.cs

IF NOT "%ERRORLEVEL%"=="0" type ..\NpcClientExample\AutogeneratedClient.cs & echo Autogeneration failed... & goto END

echo Success

:END