using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace More.Physics
{
    class Program
    {
        static Int32 Main(string[] args)
        {
            if(args.Length != 3)
            {
                Console.WriteLine("Usage: PrimeCodeGenerator.exe <namespace> <class-name> <count>");
                return 1;
            }

            String @namespace = args[0];
            String className = args[1];
            UInt32 primeCount = UInt32.Parse(args[2]);
            
            Console.WriteLine("// This file was autogenerated using the PrimeCodeGenerate.exe on {0}", DateTime.Now);
            Console.WriteLine("using System;");
            Console.WriteLine();
            Console.WriteLine("namespace {0}", @namespace);
            Console.WriteLine("{");
            Console.WriteLine("    public static class {0}", className);
            Console.WriteLine("    {");
            Console.WriteLine("        public static readonly UInt32[] FirstPrimes = new UInt32[] {");
            Console.Write("            2,3,");
            BruteForceMemoryIntensivePrimeEnumerator primeEnumerator = new BruteForceMemoryIntensivePrimeEnumerator();
            for (UInt32 i = 2; i < primeCount; i++)
            {
                if (i % 8 == 7)
                {
                    Console.WriteLine();
                    Console.Write("            ");
                }
                UInt32 prime = primeEnumerator.NextNoOverflowCheck();
                Console.Write("{0},", prime);
            }
            Console.WriteLine();
            Console.WriteLine("        };");
            Console.WriteLine("    }");
            Console.WriteLine("}");

            return 0;
        }
    }
}
