using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace More.Physics
{
    class Program
    {
        static Int32 Main(string[] args)
        {
            if(args.Length != 3)
            {
                Console.WriteLine("Usage: PrimeCodeGenerator.exe <namespace> <class-name> <count>");
                return 1;
            }

            String @namespace = args[0];
            String className = args[1];
            UInt32 primeCount = UInt32.Parse(args[2]);
            
            Console.WriteLine("// This file was autogenerated using the PrimeCodeGenerate.exe on {0}", DateTime.Now);
            Console.WriteLine("using System;");
            Console.WriteLine();
            Console.WriteLine("namespace {0}", @namespace);
            Console.WriteLine("{");
            Console.WriteLine("    public static class {0}", className);
            Console.WriteLine("    {");

            UInt32[] primes = BruteForceMemoryIntensivePrimeEnumerator.GeneratePrimes(primeCount);
            Console.WriteLine("        public const UInt32 Length = {0};", primes.Length);

            PrintPrimes(primes);

            Console.WriteLine("    }");
            Console.WriteLine("}");

            return 0;
        }

        static void PrintPrimes(UInt32[] primes)
        {
            Console.Write("        public static readonly UInt32[] Values = new UInt32[] {");
            UInt32 primeIndex = 0;

            while (true)
            {
                if (primeIndex >= primes.Length) break;
                UInt32 prime = primes[primeIndex];

                if (primeIndex % 8 == 0)
                {
                    Console.WriteLine();
                    Console.Write("            ");
                }
                Console.Write("{0},", prime);

                primeIndex++;
            }
            Console.WriteLine();
            Console.WriteLine("        };");
        }
    }
}
